// **** CHANGE TO TWEAK THE BUILD **** //

// Set this for the GitHub IMC definition repo
gradle.ext.imcGitHubRepo = 'LSTS/imc'
// Set this for the branch of the GitHub IMC definition repo
gradle.ext.imcGitHubBranch = 'f218468'
// Set this for the folder IMC definition repo
gradle.ext.imcFilePath = '../IMC'


// **** DON'T CHANGE FROM THIS LINE ON **** //
include 'core'
include 'endurance'
include 'generator'
include 'backseat'
include 'actors'
include 'imcwan'
include 'sim'
