package pt.lsts.imc4j.msg;

import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.lang.Exception;
import java.lang.String;
import java.nio.ByteBuffer;
import pt.lsts.imc4j.annotations.FieldType;
import pt.lsts.imc4j.annotations.IMCField;

/**
 * This message reports various parameters related to ocean wave characteristics, including height, direction, and period.
 */
public class WaveSpectrumParameters extends Message {
	public static final int ID_STATIC = 1018;

	/**
	 * The average height of the highest one-third of waves in a wave spectrum, representing overall sea state.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "m"
	)
	public float sig_wave_height_hm0 = 0f;

	/**
	 * The dominant direction from which waves are propagating at their peak energy level.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float wave_peak_direction = 0f;

	/**
	 * The time interval between successive wave crests at the peak energy level.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "s"
	)
	public float wave_peak_period = 0f;

	/**
	 * The significant wave height generated by wind-driven waves.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "m"
	)
	public float wave_height_wind_hm0 = 0f;

	/**
	 * The significant wave height attributed to long-period swells.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "m"
	)
	public float wave_height_swell_hm0 = 0f;

	/**
	 * The dominant period of wind-generated waves.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "s"
	)
	public float wave_peak_period_wind = 0f;

	/**
	 * The dominant period of long-period swells.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "s"
	)
	public float wave_peak_period_swell = 0f;

	/**
	 * The primary direction of wind-generated waves.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float wave_peak_direction_wind = 0f;

	/**
	 * The primary direction of swell waves.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float wave_peak_direction_swell = 0f;

	/**
	 * The average direction of all waves in the wave spectrum.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float wave_mean_direction = 0f;

	/**
	 * The mean period of ocean waves based on the spectral moment calculation.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "s"
	)
	public float wave_mean_period_tm02 = 0f;

	/**
	 * The maximum wave height observed in a given period.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "m"
	)
	public float wave_height_hmax = 0f;

	/**
	 * The height of the highest point of a wave above the mean water level.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "m"
	)
	public float wave_height_crest = 0f;

	/**
	 * The depth of the lowest point of a wave below the mean water level.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "m"
	)
	public float wave_height_trough = 0f;

	/**
	 * The longest observed wave period within a given time frame.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "s"
	)
	public float wave_period_tmax = 0f;

	/**
	 * The mean zero-crossing period of waves, an indicator of average wave duration.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "s"
	)
	public float wave_period_tz = 0f;

	/**
	 * The mean height of the highest one-third of measured waves, commonly used to describe sea conditions.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "m"
	)
	public float significant_wave_height_h1_3 = 0f;

	/**
	 * The average angular dispersion of wave energy across different directions.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float mean_spreading_angle = 0f;

	/**
	 * The first-order measure of directional wave spreading.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float first_order_spread = 0f;

	/**
	 * A parameter indicating the degree to which waves are long-crested or short-crested.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32
	)
	public float long_crestedness_parameters = 0f;

	/**
	 * The vessel’s orientation relative to true north.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float heading = 0f;

	/**
	 * The angular motion of the vessel along its transverse axis.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float pitch = 0f;

	/**
	 * The angular motion of the vessel along its longitudinal axis.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float roll = 0f;

	/**
	 * The heading measurement obtained from an external source, such as a GPS compass.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float external_heading = 0f;

	/**
	 * The standard deviation of heading measurements, indicating heading stability.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float stdev_heading = 0f;

	/**
	 * The standard deviation of pitch measurements, indicating variability in vessel movement.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float stdev_pitch = 0f;

	/**
	 * The standard deviation of roll measurements, indicating fluctuations in vessel roll motion.
	 */
	@FieldType(
			type = IMCField.TYPE_FP32,
			units = "°"
	)
	public float stdev_roll = 0f;

	public String abbrev() {
		return "WaveSpectrumParameters";
	}

	public int mgid() {
		return 1018;
	}

	public byte[] serializeFields() {
		try {
			ByteArrayOutputStream _data = new ByteArrayOutputStream();
			DataOutputStream _out = new DataOutputStream(_data);
			_out.writeFloat(sig_wave_height_hm0);
			_out.writeFloat(wave_peak_direction);
			_out.writeFloat(wave_peak_period);
			_out.writeFloat(wave_height_wind_hm0);
			_out.writeFloat(wave_height_swell_hm0);
			_out.writeFloat(wave_peak_period_wind);
			_out.writeFloat(wave_peak_period_swell);
			_out.writeFloat(wave_peak_direction_wind);
			_out.writeFloat(wave_peak_direction_swell);
			_out.writeFloat(wave_mean_direction);
			_out.writeFloat(wave_mean_period_tm02);
			_out.writeFloat(wave_height_hmax);
			_out.writeFloat(wave_height_crest);
			_out.writeFloat(wave_height_trough);
			_out.writeFloat(wave_period_tmax);
			_out.writeFloat(wave_period_tz);
			_out.writeFloat(significant_wave_height_h1_3);
			_out.writeFloat(mean_spreading_angle);
			_out.writeFloat(first_order_spread);
			_out.writeFloat(long_crestedness_parameters);
			_out.writeFloat(heading);
			_out.writeFloat(pitch);
			_out.writeFloat(roll);
			_out.writeFloat(external_heading);
			_out.writeFloat(stdev_heading);
			_out.writeFloat(stdev_pitch);
			_out.writeFloat(stdev_roll);
			return _data.toByteArray();
		}
		catch (IOException e) {
			e.printStackTrace();
			return new byte[0];
		}
	}

	public void deserializeFields(ByteBuffer buf) throws IOException {
		try {
			sig_wave_height_hm0 = buf.getFloat();
			wave_peak_direction = buf.getFloat();
			wave_peak_period = buf.getFloat();
			wave_height_wind_hm0 = buf.getFloat();
			wave_height_swell_hm0 = buf.getFloat();
			wave_peak_period_wind = buf.getFloat();
			wave_peak_period_swell = buf.getFloat();
			wave_peak_direction_wind = buf.getFloat();
			wave_peak_direction_swell = buf.getFloat();
			wave_mean_direction = buf.getFloat();
			wave_mean_period_tm02 = buf.getFloat();
			wave_height_hmax = buf.getFloat();
			wave_height_crest = buf.getFloat();
			wave_height_trough = buf.getFloat();
			wave_period_tmax = buf.getFloat();
			wave_period_tz = buf.getFloat();
			significant_wave_height_h1_3 = buf.getFloat();
			mean_spreading_angle = buf.getFloat();
			first_order_spread = buf.getFloat();
			long_crestedness_parameters = buf.getFloat();
			heading = buf.getFloat();
			pitch = buf.getFloat();
			roll = buf.getFloat();
			external_heading = buf.getFloat();
			stdev_heading = buf.getFloat();
			stdev_pitch = buf.getFloat();
			stdev_roll = buf.getFloat();
		}
		catch (Exception e) {
			throw new IOException(e);
		}
	}
}
